export enum UserRole {
  ADMIN = 'ADMIN',
  ARTISAN = 'ARTISAN',
  BUYER = 'BUYER',
  CONSUMER = 'CONSUMER',
  MODERATOR = 'MODERATOR',
}

export enum AccountStatus {
  UNVERIFIED = 'UNVERIFIED',
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
  SUSPENDED = 'SUSPENDED',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ProductStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
}

export enum AiJobType {
  PRODUCT_CATALOG_GENERATION = 'PRODUCT_CATALOG_GENERATION',
  IMAGE_ENHANCEMENT = 'IMAGE_ENHANCEMENT',
  EMBEDDING_UPDATE = 'EMBEDDING_UPDATE',
  PRICING = 'PRICING',
  SEO_GENERATION = 'SEO_GENERATION',
  MARKET_DISCOVERY = 'MARKET_DISCOVERY',
  TRANSLATION = 'TRANSLATION',
  MODERATION = 'MODERATION',
  NOTIFICATION = 'NOTIFICATION',
  NOTIFICATION_EMAIL = 'NOTIFICATION_EMAIL',
}

export enum AiJobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
}

export enum OrderType {
  RETAIL = 'RETAIL',
  WHOLESALE = 'WHOLESALE',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  IN_PRODUCTION = 'IN_PRODUCTION',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export enum RfqStatus {
  OPEN = 'OPEN',
  MATCHING = 'MATCHING',
  QUOTED = 'QUOTED',
  ACCEPTED = 'ACCEPTED',
  CLOSED = 'CLOSED',
}

export enum QuoteStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  REVISED = 'REVISED',
}

export enum MessageStatus {
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
}

export enum TrustEventType {
  IDENTITY_VERIFIED = 'IDENTITY_VERIFIED',
  BUSINESS_VERIFIED = 'BUSINESS_VERIFIED',
  ORDER_FULFILLED_ON_TIME = 'ORDER_FULFILLED_ON_TIME',
  ORDER_FULFILLED_LATE = 'ORDER_FULFILLED_LATE',
  POSITIVE_REVIEW = 'POSITIVE_REVIEW',
  NEGATIVE_REVIEW = 'NEGATIVE_REVIEW',
  DISPUTE_RESOLVED_AGAINST = 'DISPUTE_RESOLVED_AGAINST',
  DISPUTE_RESOLVED_FOR = 'DISPUTE_RESOLVED_FOR',
  RFQ_FULFILLED = 'RFQ_FULFILLED',
  LISTING_REJECTED = 'LISTING_REJECTED',
  ACCOUNT_FLAGGED = 'ACCOUNT_FLAGGED',
}

export enum DisputeCategory {
  NON_DELIVERY = 'NON_DELIVERY',
  ITEM_NOT_AS_DESCRIBED = 'ITEM_NOT_AS_DESCRIBED',
  DAMAGED_ITEM = 'DAMAGED_ITEM',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  OTHER = 'OTHER',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
}

export enum DisputeResolution {
  IN_FAVOR_OF_BUYER = 'IN_FAVOR_OF_BUYER',
  IN_FAVOR_OF_SELLER = 'IN_FAVOR_OF_SELLER',
}

export enum ReviewStatus {
  PENDING_MODERATION = 'PENDING_MODERATION',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
}

export enum NotificationCategory {
  NEW_MESSAGE = 'NEW_MESSAGE',
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE',
  RFQ_MATCH = 'RFQ_MATCH',
  QUOTE_RECEIVED = 'QUOTE_RECEIVED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  TRUST_SCORE_CHANGE = 'TRUST_SCORE_CHANGE',
  VERIFICATION_STATUS = 'VERIFICATION_STATUS',
  INVENTORY_LOW = 'INVENTORY_LOW',
  MARKET_OPPORTUNITY = 'MARKET_OPPORTUNITY',
}
