CREATE TYPE user_role AS ENUM (
  'ADMIN',
  'ARTISAN',
  'BUYER',
  'CONSUMER',
  'MODERATOR'
);

CREATE TYPE account_status AS ENUM (
  'UNVERIFIED',
  'ACTIVE',
  'LOCKED',
  'SUSPENDED'
);

CREATE TYPE verification_status AS ENUM (
  'PENDING',
  'APPROVED',
  'REJECTED'
);

CREATE TYPE product_status AS ENUM (
  'DRAFT',
  'PUBLISHED',
  'PAUSED',
  'ARCHIVED',
  'OUT_OF_STOCK'
);

CREATE TYPE ai_job_type AS ENUM (
  'PRODUCT_CATALOG_GENERATION',
  'IMAGE_ENHANCEMENT',
  'EMBEDDING_UPDATE',
  'PRICING',
  'SEO_GENERATION',
  'MARKET_DISCOVERY',
  'TRANSLATION',
  'MODERATION'
);

CREATE TYPE ai_job_status AS ENUM (
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'FAILED',
  'RETRYING'
);

CREATE TYPE order_type AS ENUM (
  'RETAIL',
  'WHOLESALE'
);

CREATE TYPE order_status AS ENUM (
  'PENDING',
  'CONFIRMED',
  'IN_PRODUCTION',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
  'RETURNED'
);

CREATE TYPE rfq_status AS ENUM (
  'OPEN',
  'MATCHING',
  'QUOTED',
  'ACCEPTED',
  'CLOSED'
);

CREATE TYPE quote_status AS ENUM (
  'PENDING',
  'ACCEPTED',
  'REJECTED',
  'EXPIRED',
  'REVISED'
);

CREATE TYPE message_status AS ENUM (
  'SENT',
  'DELIVERED',
  'READ'
);

CREATE TYPE trust_event_type AS ENUM (
  'IDENTITY_VERIFIED',
  'BUSINESS_VERIFIED',
  'ORDER_FULFILLED_ON_TIME',
  'ORDER_FULFILLED_LATE',
  'POSITIVE_REVIEW',
  'NEGATIVE_REVIEW',
  'DISPUTE_RESOLVED_AGAINST',
  'DISPUTE_RESOLVED_FOR',
  'RFQ_FULFILLED',
  'LISTING_REJECTED',
  'ACCOUNT_FLAGGED'
);

CREATE TYPE dispute_category AS ENUM (
  'NON_DELIVERY',
  'ITEM_NOT_AS_DESCRIBED',
  'DAMAGED_ITEM',
  'PAYMENT_ISSUE',
  'OTHER'
);

CREATE TYPE dispute_status AS ENUM (
  'OPEN',
  'UNDER_REVIEW',
  'ESCALATED',
  'RESOLVED'
);

CREATE TYPE dispute_resolution AS ENUM (
  'IN_FAVOR_OF_BUYER',
  'IN_FAVOR_OF_SELLER'
);

CREATE TYPE review_status AS ENUM (
  'PENDING_MODERATION',
  'PUBLISHED',
  'REJECTED'
);

CREATE TYPE notification_category AS ENUM (
  'NEW_MESSAGE',
  'ORDER_PLACED',
  'ORDER_STATUS_UPDATE',
  'RFQ_MATCH',
  'QUOTE_RECEIVED',
  'DISPUTE_OPENED',
  'TRUST_SCORE_CHANGE',
  'VERIFICATION_STATUS',
  'INVENTORY_LOW',
  'MARKET_OPPORTUNITY'
);
